### ISSUE TITLE
interpolating color

### ISSUE THREAD

**Issue by heaversm** [arturoc/ofxEasing#4]
Sorry - just trying to use this library and simultaneously get a grip on C++ by interpolating color, and I'm very confused by the documentation / example. 

I have a new color and an active color (`ofColor`). I have a function to change between the two colors, passing an R/G/B value.

```
void demoParticle::setColor(int colorR,int colorG, int colorB){
    ofColor newColor = ofColor(colorR,colorG,colorB);
    curColor = newColor;
}
```

but I want to interpolate between the two colors. I could do this with lerp:

```
        if (colorLerp > 0.0f && colorLerp < 1.0f){
            colorLerp = colorLerp + .001;
            curColor.lerp(newColor,colorLerp);
        } else {
            colorLerp = 0.0f;
        }
```

but I would love to do it with ofxEasing. I just don't understand the syntax based on the limited documentation in the readme. The example shows something very different:

```
ofxeasing::map_clamp(now, initTime, endTime, 0, endPosition, &ofxeasing::linear::easeIn);
```

Any chance you could provide a syntax based on my example above? Would be happy to do a pull request for the readme with a more thorough explanation once I understand the syntax a bit better.

**Comment by arturoc** [comment]
sorry for the late reply, the easiest for this would be to interpolate a float number between 0..1 and then use ofColor::lerp to lerp using the resulting number

**Comment by heaversm** [comment]
Was glad to get a reply at all. Thanks! That was helpful.
